# Generated by Django 4.1.4 on 2023-04-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcontent',
            name='hashid',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='reportcontent',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Like', 'Like'), ('Comment', 'Comment'), ('Follow', 'Follow'), ('Update', 'Update'), ('Notice', 'Notice')], default=None, max_length=255),
        ),
    ]
