# Generated by Django 4.2.4 on 2023-08-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoruser',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
