# Generated by Django 4.2.4 on 2023-10-10 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_userrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
