# Generated by Django 4.2.4 on 2023-08-31 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_authoruser_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authoruser',
            name='token',
        ),
    ]
