# Generated by Django 4.1.4 on 2023-04-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_reportcontent_hashid_reportcontent_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcontent',
            name='hashid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
