# Generated by Django 4.1.4 on 2023-04-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_reportcontent_hashid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcontent',
            name='hashid',
        ),
    ]
