# Generated by Django 4.1.4 on 2023-04-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_remove_reportcontent_hashid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcontent',
            name='status',
            field=models.CharField(choices=[('Solved', 'Solved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=255),
        ),
    ]
