# Generated by Django 4.2.4 on 2023-10-15 08:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_notification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.CharField(max_length=300)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userrequest',
            options={'ordering': ('-date',)},
        ),
    ]
