# Generated by Django 4.2.4 on 2023-08-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_blog_setting_userloginlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_setting',
            new_name='BlogSetting',
        ),
    ]
