# Generated by Django 4.1.4 on 2023-03-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_authoruser_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcontent',
            name='status',
            field=models.CharField(choices=[('solved', 'Solved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=255),
        ),
    ]
