# Generated by Django 4.1.4 on 2023-04-30 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_reportcontent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hash_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
