# Generated by Django 4.2.4 on 2023-08-31 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_rename_blog_setting_blogsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogsetting',
            old_name='type',
            new_name='setting',
        ),
    ]
