# Generated by Django 4.1.4 on 2023-04-30 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_category_hash_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoruser',
            name='hash_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='hash_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='hash_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='hash_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='reportcontent',
            name='hash_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
