# Generated by Django 4.2.4 on 2023-08-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_rename_type_blogsetting_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginlog',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userloginlog',
            name='was_logged',
            field=models.BooleanField(default=False),
        ),
    ]
