# Generated by Django 4.1.4 on 2023-04-01 10:41

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_alter_reportcontent_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='authoruser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='authoruser',
            name='rank',
            field=models.CharField(choices=[('Contributor', 'Contributor'), ('Author', 'Author'), ('Moderator', 'Moderator'), ('Admin', 'Admin'), ('Banned', 'Banned')], max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Hot', 'Hot'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=255),
        ),
    ]
