# Generated by Django 4.2.4 on 2023-08-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_userloginlog_note_userloginlog_was_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginlog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
