# Generated by Django 4.2.4 on 2023-08-31 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_userloginlog_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsetting',
            name='hash_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='userloginlog',
            name='hash_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
