# Generated by Django 4.1.4 on 2023-05-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_alter_comment_commenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoruser',
            name='rank',
            field=models.CharField(choices=[('Contributor', 'Contributor'), ('Author', 'Author'), ('Moderator', 'Moderator'), ('Admin', 'Admin'), ('Banned', 'Banned')], default='Contributor', max_length=255),
        ),
    ]
