# Generated by Django 4.2.4 on 2023-09-09 11:45

import Blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_blogsetting_hash_id_userloginlog_hash_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsetting',
            name='setting',
            field=models.CharField(blank=True, choices=[('forbidden-username', 'forbidden-username'), ('comment-per-page', 'comment-per-page'), ('post-per-page', 'post-per-page'), ('notice', 'notice'), ('script', 'script'), ('imgbb-apikey', 'imgbb-apikey')], default='', max_length=255),
        ),
        migrations.CreateModel(
            name='UploadedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(blank=True, default='blog/post_cover/cover.jpg', upload_to=Blog.models.post_photo)),
                ('image_url', models.URLField(blank=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
