# Generated by Django 4.2.4 on 2023-09-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_alter_blogsetting_setting_uploadedimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedimages',
            options={'verbose_name_plural': 'Uploaded Images'},
        ),
    ]
