# Generated by Django 4.1.4 on 2023-05-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_alter_authoruser_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
