# Generated by Django 4.1.4 on 2023-05-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date',)},
        ),
    ]
