# Generated by Django 4.1.4 on 2023-05-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcontent',
            name='type',
            field=models.CharField(choices=[('Comment', 'Comment'), ('User', 'User'), ('Post', 'Post'), ('Other', 'Other')], default=None, max_length=255),
        ),
    ]
