# Generated by Django 4.2.4 on 2023-09-09 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_uploadedimages_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimages',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
