# Generated by Django 4.1.4 on 2023-05-20 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_reportcontent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, choices=[('Published', 'Published'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='type',
            field=models.CharField(choices=[('Comment', 'Comment'), ('User', 'User'), ('Post', 'Post'), ('Other', 'Other')], default='Other', max_length=255),
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=255)),
                ('type', models.CharField(choices=[('Author', 'Author'), ('Other', 'Other'), ('Request', 'Request')], default='Other', max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
