# Generated by Django 4.2.4 on 2023-09-09 13:37

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_alter_uploadedimages_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to=Blog.models.post_cover),
        ),
    ]
