# Generated by Django 4.1.4 on 2023-05-20 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_alter_comment_status_alter_reportcontent_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='hash_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Public', 'Public'), ('Draft', 'Draft')], default='Public', max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_series', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='authoruser',
            name='series',
            field=models.ManyToManyField(related_name='user_series', to='Blog.series'),
        ),
        migrations.AddField(
            model_name='post',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.series'),
        ),
    ]
