# Generated by Django 4.1.4 on 2023-05-20 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_userrequest_hash_id_series_authoruser_series_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.AddField(
            model_name='series',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
