# Generated by Django 4.1.4 on 2023-06-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_alter_series_options_series_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='authoruser',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='user_series', to='Blog.series'),
        ),
    ]
