# Generated by Django 4.2.4 on 2023-09-21 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_remove_post_like_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='user_dislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
