# Generated by Django 4.1.4 on 2023-06-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0017_series_slug_alter_authoruser_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoruser',
            name='bio',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
