# Generated by Django 4.2.4 on 2023-09-30 13:05

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0018_alter_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Blog.models.post_photo),
        ),
    ]
