# Generated by Django 4.1.4 on 2023-06-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0018_alter_authoruser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoruser',
            name='website_url',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
