# Generated by Django 4.2.4 on 2023-09-30 13:07

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0019_alter_uploadedimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimages',
            name='image',
            field=models.ImageField(blank=True, default='blog/post_cover/cover.jpg', upload_to=Blog.models.post_photo),
        ),
    ]
