# Generated by Django 4.1.4 on 2023-06-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0019_authoruser_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoruser',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
