# Generated by Django 4.1.4 on 2023-06-07 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0020_alter_authoruser_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoruser',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='user_follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
