# Generated by Django 4.2.4 on 2023-09-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0020_alter_uploadedimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimages',
            name='image_url',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
