# Generated by Django 4.1.4 on 2023-06-07 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0021_authoruser_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoruser',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='user_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
