# Generated by Django 4.1.4 on 2023-06-07 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0022_alter_authoruser_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_in_series', to='Blog.series'),
        ),
        migrations.AlterField(
            model_name='series',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
