# Generated by Django 4.1.4 on 2023-06-08 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0023_alter_post_series_alter_series_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoruser',
            name='mute_list',
            field=models.ManyToManyField(blank=True, related_name='muted', to=settings.AUTH_USER_MODEL),
        ),
    ]
