# Generated by Django 4.1.4 on 2023-06-08 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0025_alter_authoruser_follower_alter_authoruser_mute_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoruser',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='user_following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authoruser',
            name='mute_list',
            field=models.ManyToManyField(blank=True, related_name='muted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authoruser',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='user_series', to='Blog.series'),
        ),
    ]
