# Generated by Django 4.1.4 on 2023-06-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0026_alter_authoruser_follower_alter_authoruser_mute_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, choices=[('Published', 'Published'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Published', max_length=255, null=True),
        ),
    ]
